// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty;

  angular.module('contactModule').controller('ContactListCtrl', [
    '$scope', '$http', '$location', 'contactManager', '$log', 'ModelBase', 'Restangular', function($scope, $http, $location, contactManager, $log, ModelBase, Restangular) {
      var promise;
      $scope.title = "联系人";
      $scope.icon = "./img/128px/layers_128px.png";
      $scope.backUrl = "#/home";
      $scope.isAdvanceSearchCollapsed = true;
      $scope.toggleAdvanceSearch = function() {
        if ($scope.isAdvanceSearchCollapsed) {
          return $scope.isAdvanceSearchCollapsed = false;
        } else {
          return $scope.isAdvanceSearchCollapsed = true;
        }
      };
      $scope.currentPage = 1;
      $scope.contactMatch = function(query) {
        return function(item) {
          if (query == null) {
            return true;
          }
          return item.name.indexOf(query) >= 0 || item.description.indexOf(query) >= 0;
        };
      };
      $scope.progressBar.start();
      $scope.progressBar.set(50);
      promise = contactManager.loadContactList();
      return promise.then(function(contacts) {
        $scope.items = contacts;
        $log.log(contacts);
        return $scope.progressBar.end();
      }, function(reason) {
        $scope.progressBar.end();
        if (reason.status === 404) {
          return $rootScope.$broadcast('errorHappened', reason.status, $location.url());
        } else if (reason.status === 401 || reason.status === 403) {
          $location.url("/login?query=" + encodeURIComponent($location.url()));
          return $location.replace();
        } else {
          return $log.log("Error Code: " + reason.status + ", Message: " + reason.data);
        }
      }, null);
    }
  ]).controller('ContactDetailCtrl', [
    '$scope', '$http', '$q', '$routeParams', 'contactManager', '$location', '$log', 'ModelBase', function($scope, $http, $q, $routeParams, contactManager, $location, $log, ModelBase) {
      var dataFields;
      $scope.progressBar.start();
      $scope.progressBar.set(50);
      $scope.backUrl = "#/contact";
      $scope.contact = null;
      $scope.showToolbar = true;
      $scope.showRefresh = true;
      $scope.newLink = {
        type: "Supplier",
        name: ""
      };
      $scope.contactDatas = [];
      dataFields = [];
      $scope.unsetFields = [];
      $scope.changeType = function(type) {
        return $scope.newLink.type = type;
      };
      $scope.addLink = function() {
        $scope.newLink.modifiedDate = new Date();
        $scope.contact.links.push(angular.copy($scope.newLink));
        return $scope.newLink = {
          type: "Supplier",
          name: ""
        };
      };
      $scope.addData = function() {
        var newData;
        newData = angular.copy($scope.newData);
        $scope.newData.key = "";
        $scope.newData.value = "";
        return $scope.contactDatas.push(newData);
      };
      $scope.save = function() {
        var contactData, newContact, newContactDeffered, promises, updatedContactData, updatedContactDataDeffered, _i, _len, _ref, _ref1;
        $log.log($scope.contact);
        promises = [];
        $scope.progressBar.start();
        $scope.progressBar.set(20);
        updatedContactDataDeffered = $q.defer();
        promises.push(updatedContactDataDeffered);
        updatedContactData = contactManager.initContactData();
        updatedContactData.url = $scope.contact.data.url;
        updatedContactData.contact = $scope.contact.data.contact;
        updatedContactData.createdBy = $scope.contact.data.createdBy;
        updatedContactData.modifiedBy = 'cage';
        _ref = $scope.contactDatas;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          contactData = _ref[_i];
          if ((_ref1 = contactData.key) === 'surname' || _ref1 === 'givenname' || _ref1 === 'company' || _ref1 === 'department' || _ref1 === 'title' || _ref1 === 'phone' || _ref1 === 'mobile' || _ref1 === 'fax' || _ref1 === 'origin' || _ref1 === 'email' || _ref1 === 'address' || _ref1 === 'birthday' || _ref1 === 'region' || _ref1 === 'website' || _ref1 === 'qq' || _ref1 === 'weibo' || _ref1 === 'im') {
            (function(contactData) {
              return updatedContactData[contactData.key] = contactData.value;
            })(contactData);
          }
        }
        updatedContactData.update(function(data) {
          return updatedContactDataDeffered.resolve(data);
        }, function(error) {
          return updatedContactDataDeffered.reject(error);
        });
        newContact = new ModelBase();
        newContact.url = $scope.contact.url;
        newContact.avator = $scope.contact.avator;
        newContact.name = $scope.contact.name;
        newContact.createdBy = $scope.contact.createdBy;
        newContact.modifiedBy = 'cage';
        newContact.description = $scope.contact.description;
        newContact.data = $scope.contact.data.url;
        newContactDeffered = $q.defer();
        promises.push(newContactDeffered);
        newContact.update(function(data) {
          return newContactDeffered.resolve(data);
        }, function(error) {
          return newContactDeffered.reject();
        });
        return $q.all(promises).then($scope.reload);
      };
      $scope.reload = function() {
        var promise;
        promise = contactManager.loadContact($routeParams.id);
        return promise.then(function(contactData) {
          var propName, propValue, _ref;
          $scope.contact = contactData;
          $scope.contactDatas = [];
          $scope.unsetFields = [];
          dataFields = [];
          _ref = contactData.data;
          for (propName in _ref) {
            if (!__hasProp.call(_ref, propName)) continue;
            propValue = _ref[propName];
            if (!(propName !== "id" && propName !== "contactname" && propName !== "contact" && propName !== "url" && propName !== "createdDate" && propName !== "createdBy" && propName !== "modifiedDate" && propName !== "modifiedBy")) {
              continue;
            }
            dataFields.push(propName);
            if ((propValue != null) && propValue !== "") {
              $scope.contactDatas.push({
                key: propName,
                value: propValue
              });
            } else {
              $scope.unsetFields.push(propName);
            }
          }
          $scope.title = contactData.name;
          return $scope.progressBar.end();
        }, function(reason) {
          $scope.progressBar.end();
          if (reason.status === 404) {
            return $rootScope.$broadcast('errorHappened', reason.status, $location.url());
          } else if (reason.status === 401 || reason.status === 403) {
            return $location.url("/login");
          } else {
            return $log.log("Error Code: " + reason.status + ", Message: " + reason.data);
          }
        }, null);
      };
      $scope.previousId = function() {
        var previousId;
        previousId = contactManager.getPreviousContact($scope.contact.id);
        if (previousId !== $scope.contact.id && angular.isNumber(previousId)) {
          return $location.url("/contact/" + previousId);
        }
      };
      $scope.nextId = function() {
        var nextId;
        nextId = contactManager.getNextContact($scope.contact.id);
        if (nextId !== $scope.contact.id && angular.isNumber(nextId)) {
          return $location.url("/contact/" + nextId);
        }
      };
      $scope.refreshLinks = function() {
        return $http.get('../mockData/links.json').success(function(data, status) {
          return $scope.contact.links = data;
        });
      };
      return $scope.reload();
    }
  ]).controller('NewContactCtrl', [
    '$scope', '$http', '$log', function($scope, $http, $log) {
      $scope.backUrl = "#/contact";
      $scope.contact = {
        info: {},
        avator: "./img/default_avatar.png",
        links: [],
        comments: []
      };
      $scope.title = "新建联系人";
      $scope.showToolbar = false;
      $scope.showRefresh = false;
      $scope.newLink = {
        type: "Supplier",
        name: ""
      };
      $scope.changeType = function(type) {
        return $scope.newLink.type = type;
      };
      $scope.addLink = function() {
        $scope.newLink.modifiedDate = new Date();
        $scope.contact.links.push($scope.newLink);
        return $scope.newLink = {
          type: "Supplier",
          name: ""
        };
      };
      return $scope.save = function() {
        return $log.log($scope.contact);
      };
    }
  ]);

}).call(this);
