platform :ios, '7.0'
pod 'Reachability', '~> 3.1.1'
pod 'Mantle', '~> 1.3.1'
pod 'TSMessages', '~> 0.9.4'
pod 'ReactiveCocoa', '~> 2.2'
pod 'ASIHTTPRequest', '~> 1.8.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'JSONKit-NoWarning', '~> 1.2'


