// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('taskModule').controller('TaskListCtrl', [
    '$scope', '$rootScope', '$http', '$log', 'Restangular', 'erplite.utils', function($scope, $rootScope, $http, $log, Restangular, utils) {
      var validate;
      $scope.title = "任务";
      $scope.backUrl = "#/home";
      $scope.addUrl = '#/task/new';
      $scope.isAdvanceSearchCollapsed = true;
      $scope.toggleAdvanceSearch = function() {
        if ($scope.isAdvanceSearchCollapsed) {
          return $scope.isAdvanceSearchCollapsed = false;
        } else {
          return $scope.isAdvanceSearchCollapsed = true;
        }
      };
      $scope.currentPage = 1;
      $scope.calendarHeight = 220;
      $scope.newTask = {};
      $scope.progressBar.start();
      $scope.progressBar.set(50);
      Restangular.all('tasks').getList().then(function(tasks) {
        $scope.tasks = tasks;
        return $scope.progressBar.end();
      }, function(reason) {
        utils.HttpHandle(reason);
        return $scope.progressBar.end();
      }, function() {
        return $scope.progressBar.end();
      });
      $scope.dayClick = function(date, jsevent, cordinator) {
        console.log(date);
        $scope.newTask.due = date.day.format('YYYY-MM-DD');
        $scope.newTaskDueStr = date.day.format('YYYY-MM-DD');
        return $scope.isCalOpen = false;
      };
      validate = function(task) {
        return true;
      };
      $scope.confirmAdd = function(newTask) {
        $scope.progressBar.start();
        newTask.createdBy = 'admin';
        newTask.modifiedBy = 'admin';
        if (!newTask.owner) {
          newTask.owner = 'admin';
        }
        if (validate(newTask)) {
          return $scope.tasks.post(newTask).then(function(data) {
            $scope.tasks.push(data);
            $scope.newTask = {};
            return $scope.progressBar.end();
          }, function(reason) {
            utils.HttpHandle(reason);
            return $scope.progressBar.end();
          }, null);
        }
      };
      $scope.beginEditing = function(task) {
        $scope.isNewTaskPanelShow = false;
        if ($scope.currentEditingTask != null) {
          $scope.currentEditingTask.editing = false;
        }
        $scope.currentEditingTask = task;
        $scope.currentEditingTask.editing = true;
        if (task.due != null) {
          return task.dueDate = moment(task.due)._d;
        }
      };
      $scope.open = function($event, task) {
        $event.preventDefault();
        $event.stopPropagation();
        return task.opened = true;
      };
      $scope.dateOptions = {
        formatYear: 'yy',
        startingDay: 1
      };
      $scope.openMore = function($event, task) {
        $event.preventDefault();
        return $event.stopPropagation();
      };
      $scope.confirmEdit = function(task) {
        task.editing = false;
        if (task.dueDate != null) {
          task.due = moment(task.dueDate).format('YYYY-MM-DD');
        }
        return task.put();
      };
      $scope.cancelEdit = function(task) {
        return task.get().then(function(oldTask) {
          return angular.extend(task, oldTask);
        });
      };
      return $scope.changeStatus = function($event, task) {
        task.status = task.status === 'closed' ? 'open' : 'closed';
        task.put();
        $event.preventDefault();
        return $event.stopPropagation();
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=taskControllers.map
