// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('taskModule').controller('TaskListCtrl', [
    '$scope', '$rootScope', '$http', '$log', 'Restangular', 'erplite.utils', function($scope, $rootScope, $http, $log, Restangular, utils) {
      $scope.title = "任务";
      $scope.backUrl = "#/home";
      $scope.isAdvanceSearchCollapsed = true;
      $scope.toggleAdvanceSearch = function() {
        if ($scope.isAdvanceSearchCollapsed) {
          return $scope.isAdvanceSearchCollapsed = false;
        } else {
          return $scope.isAdvanceSearchCollapsed = true;
        }
      };
      $scope.currentPage = 1;
      $scope.progressBar.start();
      $scope.progressBar.set(50);
      return Restangular.all('tasks').getList().then(function(tasks) {
        $scope.tasks = tasks;
        return $scope.progressBar.end();
      }, function(reason) {
        utils.HttpHandle(reason);
        return $scope.progressBar.end();
      }, function() {
        return $scope.progressBar.end();
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=taskControllers.map
