// Generated by CoffeeScript 1.7.1
(function() {
  var erpControllers;

  erpControllers = angular.module('erpControllers', ['erpServices']);

  erpControllers.controller('RootCtrl', [
    '$scope', '$timeout', 'erpSettings', function($scope, $timeout, erpSettings) {
      $scope.title = "";
      $scope.hasError = false;
      $scope.progressShow = false;
      $scope.progressValue = 0;
      $scope.progressType = 'success';
      $scope.progressBar = {
        blink: function() {
          $timeout(function() {
            $scope.progressShow = true;
            return $scope.progressValue = 50;
          }, 500);
          $timeout(function() {
            return $scope.progressValue = 100;
          }, 1000);
          $timeout(function() {
            return $scope.progressShow = false;
          }, 1500);
          return $timeout(function() {
            return $scope.progressValue = 0;
          }, 2500);
        },
        start: function() {
          $scope.progressShow = true;
          return $scope.progressValue = 0;
        },
        set: function(progress) {
          return $scope.progressValue = progress;
        },
        end: function() {
          $scope.progressValue = 100;
          $scope.progressShow = false;
          return $timeout(function() {
            return $scope.progressValue = 0;
          }, 1000);
        }
      };
      return $scope.erpSettings = erpSettings;
    }
  ]);

  erpControllers.controller('HomeCtrl', [
    '$scope', '$http', '$location', '$rootScope', function($scope, $http, $location, $rootScope) {
      $scope.title = "Welcome, Kaiqi";
      $scope.hasError = false;
      $scope.progressBar.start();
      $scope.progressBar.set(50);
      $http.get('../mockData/applist.json').success(function(data, status) {
        $scope.apps = data;
        return $scope.progressBar.end();
      }).error(function(data, status) {
        $scope.hasError = true;
        $scope.progressBar.end();
        if (status === "404") {
          $scope.error = "404 not found";
          return $rootScope.$broadcast('errorHappened', status, $location.url());
        } else if (status === "401") {
          return $location.url("/login");
        } else {
          return $scope.error = "Error Code: " + status + ", Message: " + data;
        }
      });
    }
  ]);

  erpControllers.controller('LoginCtrl', [
    '$scope', '$http', 'security', '$routeParams', '$location', function($scope, $http, security, $routeParams, $location) {
      if ($location.url() === '/logout') {
        security.clearAccessToken();
        $http.get($scope.erpSettings.apiHost + '/accounts/logout').success(function() {
          return console.log('logout');
        });
      }
      $scope.rememberMe = false;
      $scope.login = function() {
        var loginParam;
        loginParam = {
          username: $scope.username,
          password: $scope.password
        };
        return $http.post($scope.erpSettings.apiHost + '/login/', loginParam).success(function(data) {
          var headers, token;
          console.log(data);
          token = data.token;
          headers = {
            'Authorization': token
          };
          security.setHttpHeader(headers);
          if ($routeParams.query != null) {
            $location.url(encodeURIComponent($routeParams.query));
            return $location.replace();
          } else {
            $location.url('/home');
            return $location.replace();
          }
        }).error(function() {
          return console.log('error');
        })["finally"](function() {
          return console.log('finally');
        });
      };
    }
  ]);

  erpControllers.controller('SignupCtrl', [
    '$scope', '$http', 'security', '$routeParams', '$location', function($scope, $http, security, $routeParams, $location) {
      $scope.signup = function() {
        var signupParam;
        signupParam = "csrfmiddlewaretoken=" + security.getCSRF() + "&username=" + $scope.username + "&email=" + $scope.email + "&password=" + $scope.password;
        $http.post($scope.erpSettings.apiHost + '/accounts/register', signupParam, {
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
          }
        }).success(function() {
          if ($routeParams.query != null) {
            $location.url(encodeURIComponent($routeParams.query));
            return $location.replace();
          } else {
            $location.url('/home');
            return $location.replace();
          }
        }).error(function() {
          return console.log('error');
        })["finally"](function() {
          return console.log('finally');
        });
        return security.saveCookie();
      };
    }
  ]);

  erpControllers.controller('404Ctrl', ['$scope', '$http', function($scope, $http) {}]);

}).call(this);
