// Generated by CoffeeScript 1.7.1
(function() {
  var erpControllers;

  erpControllers = angular.module('erpControllers', ['erpServices']);

  erpControllers.controller('RootCtrl', [
    '$scope', '$timeout', function($scope, $timeout) {
      $scope.title = "";
      $scope.hasError = false;
      $scope.progressShow = false;
      $scope.progressValue = 0;
      $scope.progressType = 'success';
      $scope.progressBar = {
        blink: function() {
          $timeout(function() {
            $scope.progressShow = true;
            return $scope.progressValue = 50;
          }, 500);
          $timeout(function() {
            return $scope.progressValue = 100;
          }, 1000);
          $timeout(function() {
            return $scope.progressShow = false;
          }, 1500);
          return $timeout(function() {
            return $scope.progressValue = 0;
          }, 2500);
        },
        start: function() {
          $scope.progressShow = true;
          return $scope.progressValue = 0;
        },
        set: function(progress) {
          return $scope.progressValue = progress;
        },
        end: function() {
          $scope.progressValue = 100;
          $scope.progressShow = false;
          return $timeout(function() {
            return $scope.progressValue = 0;
          }, 1000);
        }
      };
    }
  ]);

  erpControllers.controller('HomeCtrl', [
    '$scope', '$http', '$location', '$rootScope', function($scope, $http, $location, $rootScope) {
      $scope.title = "Welcome, Kaiqi";
      $scope.hasError = false;
      $scope.progressBar.start();
      $scope.progressBar.set(50);
      $http.get('../mockData/applist.json').success(function(data, status) {
        $scope.apps = data;
        return $scope.progressBar.end();
      }).error(function(data, status) {
        $scope.hasError = true;
        $scope.progressBar.end();
        if (status === "404") {
          $scope.error = "404 not found";
          return $rootScope.$broadcast('errorHappened', status, $location.url());
        } else if (status === "401") {
          return $location.url("/login");
        } else {
          return $scope.error = "Error Code: " + status + ", Message: " + data;
        }
      });
    }
  ]);

  erpControllers.controller('LoginCtrl', [
    '$scope', '$http', 'security', function($scope, $http, security) {
      $scope.rememberMe = false;
      $scope.login = function() {
        var loginParam;
        loginParam = {
          username: $scope.username,
          password: $scope.password,
          rememberMe: $scope.rememberMe
        };
        return security.saveCookie();
      };
    }
  ]);

  erpControllers.controller('404Ctrl', ['$scope', '$http', function($scope, $http) {}]);

}).call(this);
