// Generated by CoffeeScript 1.7.1
var erpFilters;

erpFilters = angular.module('erpFilters', []);

erpFilters.filter('zero2display', function() {
  return function(input) {
    if (input === 0) {
      return 'none';
    } else {
      return 'visible';
    }
  };
});

erpFilters.filter('boolean2display', function() {
  return function(input) {
    if (input) {
      return 'visible';
    } else {
      return 'none';
    }
  };
});

erpFilters.filter('type2class', function() {
  return function(input) {
    var result;
    result = null;
    switch (input) {
      case "Supplier":
        result = "glyphicon glyphicon-barcode";
        break;
      case "Task":
        result = "glyphicon glyphicon-pushpin";
        break;
      default:
        result = "glyphicon glyphicon-link";
    }
    return result;
  };
});
