// Generated by CoffeeScript 1.7.1
(function() {
  document.write('<script src="/app/bower_components/jquery/dist/jquery.min.js"></script>');

  document.write('<script src="/app/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>');

  document.write('<script src="/app/bower_components/danialfarid-angular-file-upload/dist/angular-file-upload-shim.min.js"></script>');

  document.write('<script src="/app/bower_components/angular/angular.min.js"></script>');

  document.write('<script src="/app/bower_components/danialfarid-angular-file-upload/dist/angular-file-upload.min.js"></script>');

  document.write('<script src="/app/bower_components/angular-route/angular-route.min.js"></script>');

  document.write('<script src="/app/bower_components/angular-cookies/angular-cookies.min.js"></script>');

  document.write('<script src="/app/bower_components/iCheck/icheck.min.js"></script>');

  document.write('<script src="/app/bower_components/angular-animate/angular-animate.min.js"></script>');

  document.write('<script src="/app/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>');

  document.write('<script src="/app/bower_components/lodash/dist/lodash.min.js"></script>');

  document.write('<script src="/app/bower_components/restangular/dist/restangular.min.js"></script>');

  document.write('<script src="/app/bower_components/momentjs/min/moment.min.js"></script>');

  document.write('<script src="/app/bower_components/twix/bin/twix.min.js"></script>');

  document.write('<script src="Common/js/init.js"></script>');

  document.write('<script src="Common/js/factories.js"></script>');

  document.write('<script src="js/animations.js"></script>');

  document.write('<script src="js/app.js"></script>');

  document.write('<script src="js/controllers.js"></script>');

  document.write('<script src="js/filters.js"></script>');

  document.write('<script src="js/directives.js"></script>');

  document.write('<script src="js/services.js"></script>');

  document.write('<script src="Contact/js/init.js"></script>');

  document.write('<script src="Contact/js/contactModels.js"></script>');

  document.write('<script src="Contact/js/contactManagers.js"></script>');

  document.write('<script src="Contact/js/contactControllers.js"></script>');

  document.write('<script src="Calendar/js/init.js"></script>');

  document.write('<script src="Calendar/js/calendarControllers.js"></script>');

  document.write('<script src="Calendar/js/calendarDirectives.js"></script>');

  document.write('<script src="Task/js/init.js"></script>');

  document.write('<script src="Task/js/taskControllers.js"></script>');

}).call(this);

//# sourceMappingURL=main.map
