// Generated by CoffeeScript 1.7.1
(function() {
  var erpServices;

  erpServices = angular.module('erpServices', ['ngCookies']);

  erpServices.factory('security', [
    '$cookies', '$http', function($cookies, $http) {
      return {
        setHttpHeader: function(header) {
          $http.defaults.headers.common.Authorization = "Token " + header.Authorization;
          return $cookies.access_token = header.Authorization;
        },
        getCSRF: function() {
          return $cookies.csrftoken;
        },
        clearAccessToken: function() {
          delete $http.defaults.headers.common["Authorization"];
          return delete $cookies["access_token"];
        },
        restoreToken: function() {
          if ($cookies.access_token != null) {
            return $http.defaults.headers.common.Authorization = "Token " + $cookies.access_token;
          }
        }
      };
    }
  ]);

}).call(this);
