// Generated by CoffeeScript 1.7.1
var erpDirectives;

erpDirectives = angular.module('erpDirectives', []);


/*
  angular directive erp-icheck

  @description icheck is a plugin of jquery for beautifying checkbox &amp; radio, now I complied it with angular directive
  @require jquery, icheck
  @example <input type="radio" ng-model="paomian" value="kangshifu" erp-icheck>
           <input type="checkbox" class="icheckbox" name="mantou" ng-model="mantou" erp-icheck checked>
 */

erpDirectives.directive('erpIcheck', function($document) {
  return {
    restrict: 'A',
    require: '?ngModel',
    link: function($scope, $element, $attrs, $ngModel) {
      if (!$ngModel) {
        return;
      }
      return $element.iCheck({
        labelHover: false,
        cursor: true,
        checkboxClass: 'icheckbox_flat-blue',
        radioClass: 'iradio_flat-blue'
      }).on('ifClicked', function(event) {
        if ($attrs.type === "checkbox") {
          return $scope.$apply(function() {
            return $ngModel.$setViewValue($ngModel.$modelValue ? $ngModel.$modelValue : false);
          });
        } else {
          return $scope.$apply(function() {
            return $ngModel.$setViewValue($attrs.value);
          });
        }
      });
    }
  };
});

erpDirectives.directive('erpImgLoading', function($document) {
  return {
    restrict: 'A',
    link: function($scope, $element, $attrs) {
      $element.addClass("beforeLoaded");
      return $element.on('load', function(event) {
        $element.removeClass("beforeLoaded");
        return $element.addClass("afterLoaded");
      });
    }
  };
});
