// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('calendarModule').controller('CalendarCtrl', [
    '$scope', '$log', function($scope, $log) {
      var events;
      $scope.title = "Calendar";
      events = [
        {
          title: "event1",
          start: new Date(),
          end: new Date(),
          allDay: false
        }, {
          title: "event1",
          start: new Date(),
          end: new Date(),
          allDay: false
        }, {
          title: "event1",
          start: new Date(),
          end: new Date(),
          allDay: false
        }, {
          title: "event1",
          start: new Date(),
          end: new Date(),
          allDay: false
        }, {
          title: "event1",
          start: new Date(),
          end: new Date(),
          allDay: false
        }
      ];
      $scope.eventSource = [events];
      $scope.dayClick = function(date, dayEvents, jsEvent) {
        $scope.dayEvents = dayEvents;
        $log.log(jsEvent);
        return $log.log(date);
      };
      $scope.dayHover = function(date, dayEvents, jsEvent) {
        $scope.dayEvents = dayEvents;
        $log.log(jsEvent);
        return $log.log(date);
      };
      $scope.removeEvent = function(event) {
        if (events.indexOf(event) > -1) {
          return events.slice(events.indexOf(event), 0);
        }
      };
      return $scope.addEvent = function(title, start, end) {
        return events.push({
          start: start,
          end: end,
          title: title,
          allDay: false
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=calendarControllers.map
